apiRules:
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: ^UnityEngine
    type: Namespace  
- exclude:
    uidRegex: ^System
    type: Namespace 
- exclude:
    uidRegex: .*
    type: Namespace